    // ================= HOW TO PLAY =================
    const howto=el('ns_howto');
    function showHowTo(firstRun){
      howto.innerHTML=''; howto.style.display='block'; howto.scrollTop=0; howto.style.position='fixed'; howto.style.zIndex='99999'; var _hx=document.createElement('div'); _hx.textContent='✕'; _hx.style.cssText='position:fixed;top:10px;right:12px;z-index:100000;width:30px;height:30px;line-height:30px;text-align:center;font-size:16px;font-weight:bold;color:#0b0910;background:#c6e84a;border-radius:8px;cursor:pointer;box-shadow:0 2px 6px rgba(0,0,0,0.5);'; _hx.onclick=function(){ howto.style.display='none'; try{ localStorage.setItem('ns_howto_seen','1'); }catch(e){} }; howto.appendChild(_hx);
      const pad=mk('div','padding:16px 14px 18px;');
      pad.appendChild(mk('div',FS(12,'#c6e84a')+'text-align:center;margin-bottom:14px;letter-spacing:1px;','HOW TO PLAY'));
      const rows=[
        ['✦ FLICK','Drag back from the ball and release — like a slingshot. The longer you drag, the longer the aim arrow and the harder the shot.'],
        ['✦ SCORE','Flick the ball into your opponent’s goal — the net at the other end of the pitch. First team to hit the target number of goals wins the match.'],
        ['✦ POSSESSION','Hit one of YOUR OWN players and you keep the turn — up to 3 flicks per turn. Miss (or after the 3rd flick), the turn passes to your opponent.'],
        ['✦ STAMINA','Your legs tire through the turn: the 1st flick is full power, each one after is weaker — 100% → 75% → 50%. The aim arrow shows it: green (fresh) fading to red (tired), and it gets shorter too. Fresh legs every new turn. (No stamina in Practice.)'],
        ['✦ GOALIE','Each side has a keeper that auto-tracks the ball across its goal. Aim for the corners.'],
        ['✦ SETUP','Before kickoff, drag your outfield players to position them how you like. Your goalkeeper isn’t one of them — it stays on its line and moves on its own to block shots, so you don’t set it up. Pick your team, kit, pitch and formation on the setup screen before you play.'],
        ['✦ ABILITIES','Special powers — like a harder shot, a bigger keeper, or a ball that curves. You gain one when you score: EXHIBITION lets you pick one of three, free. TOURNAMENT and the COIN RUSH toggle run on coins — hit gold tokens to fill a shared pot, score to bank it, then spend in the ability shop. Each one, and how rare it is, is listed below.'],
        ['✦ ABILITY SLOTS','Each team has 3 slots for abilities. A new one you win drops into an empty slot. You can also tap one of your own scoreboard slots any time to pick or change an ability. When all 3 are full, your next win lets you swap one out.'],
        ['✦ COMEBACK','Losing by 2 or more goals? You get a FREE random ability to help you fight back — no picking here, fate decides — and the further behind you are, the better your chance of a rare, powerful one. It resets once you level the score.'], ['✦ PENALTY SHOOTOUT','The match is not over yet! A 1-goal finish gives the losing team a LAST CHANCE — tie it within a 3-flick limit and take the match to a penalty shootout.']
      ];
      rows.forEach(([h,b])=>{ const box=mk('div','margin-bottom:11px;'); box.appendChild(mk('div',FS(8,'#f4e9c8')+'margin-bottom:4px;',h)); box.appendChild(mk('div',"font-size:10px;line-height:1.7;color:#b7a9c8;",b)); pad.appendChild(box); }); try{ if(typeof TACTICS!=='undefined'){ var abx=mk('div','margin-top:2px;'); abx.appendChild(mk('div',FS(8,'#f4e9c8')+'margin-bottom:7px;','✦ ALL ABILITIES')); (function(){ var _T=AB_TIERS.slice().reverse().map(function(t){ return [t.name,t.col]; }); var _lg=mk('div','font-size:10px;line-height:1.7;color:#b7a9c8;margin:0 0 9px 0;'); _lg.appendChild(mk('span','','Rarer abilities are won less often: ')); _T.forEach(function(tr,ii){ _lg.appendChild(mk('span','color:'+tr[1]+';font-weight:bold;',tr[0])); if(ii<_T.length-1) _lg.appendChild(mk('span','color:#6b6376;',' · ')); }); abx.appendChild(_lg); })(); TACTICS.slice().sort(function(_a,_b){ return abWeight(_b.id)-abWeight(_a.id); }).forEach(function(t){ var _tt=abTier(t.id), _rr=[_tt.name,_tt.col]; var row=mk('div','display:flex;align-items:center;gap:9px;margin-bottom:8px;'); var ic=mk('div','width:40px;height:40px;flex:0 0 auto;background-size:86%;background-repeat:no-repeat;background-position:center;image-rendering:pixelated;display:flex;align-items:center;justify-content:center;font-size:20px;'); if(typeof ICON_SRC!=='undefined' && ICON_SRC[t.id]){ ic.style.backgroundImage='url('+ICON_SRC[t.id]+')'; } else { ic.textContent=t.icon; } var tx=mk('div','flex:1;'); var _nm=mk('div','display:flex;justify-content:space-between;align-items:baseline;gap:8px;'); _nm.appendChild(mk('span',FS(8,'#c6e84a'),t.name)); _nm.appendChild(mk('span','font-size:9px;font-weight:bold;letter-spacing:0.5px;white-space:nowrap;color:'+_rr[1]+';',_rr[0])); tx.appendChild(_nm); tx.appendChild(mk('div','font-size:10px;line-height:1.5;color:#b7a9c8;',t.desc)); row.appendChild(ic); row.appendChild(tx); abx.appendChild(row); }); pad.appendChild(abx); } }catch(e){} 
      const ok=mk('button',"margin-top:6px;width:100%;"+FS(11,'#0b1a0e')+"background:#c6e84a;border:2px solid #e6ff7a;padding:9px;cursor:pointer;", firstRun?'GOT IT ▸':'CLOSE');
      ok.onclick=()=>{ howto.style.display='none'; try{ localStorage.setItem('ns_howto_seen','1'); }catch(e){} };
      pad.appendChild(ok);
      howto.appendChild(pad);
    }

