    /* ---- TROPHY COLLECTION ----------------------------------------------
       Nine hand-generated pixel-art cups: 3 season finals x bronze/silver/gold
       (easy/med/hard). Each cup wears the hazards of the final you beat. Art is
       generated by tools/gen-trophies.mjs and shipped to
       assets/generated/trophy-s{1,2,3}-{bronze,silver,gold}.png, preloaded into
       NS_TROPHIES (see 12-draw.js). A trophy is "earned" once that season has
       been cleared at that difficulty (royDiffsFor). Shown in the achievements
       overlay and blitted onto the Royale map summit. */
    var TROPHY_METALS=['bronze','silver','gold'];        // easy / med / hard
    var TROPHY_SEASONS=['S1 THE FINAL','S2 THE TURF','S3 SPORTS DAY'];
    var TROPHY_DIFFS=['easy','med','hard'];
    // The preloaded Image for season index si (0-2) and tier ti (0-2), or null.
    function spTrophyImg(si,ti){ try{ return NS_TROPHIES['s'+(si+1)+'-'+TROPHY_METALS[ti]]||null;
    }catch(e){ return null; } }
    // How many of the 9 trophies the player has earned (season+diff cleared).
    function spTrophyCount(){ try{ var n=0;
    for(var s=1;s<=3;s++){ var d=royDiffsFor(s)||[];
    for(var t=0;t<3;t++){ if(d.indexOf(TROPHY_DIFFS[t])>=0) n++; } } return n;
    }catch(e){ return 0; } }
    // A ready-to-place DOM cell carrying one trophy at pixel size px. Locked
    // trophies render greyed + dimmed with a small padlock so the shape still
    // teases what's on offer.
    function spTrophyEl(si,ti,lit,px){ var cell=mk('div','position:relative;width:'+px+'px;height:'+px+'px;');
    var im=spTrophyImg(si,ti);
    var img=mk('img','width:100%;height:100%;image-rendering:pixelated;display:block;'+(lit?'':'filter:grayscale(1) brightness(0.4) contrast(0.9);opacity:0.6;'));
    try{ if(im&&im.src) img.src=im.src; }catch(e){}
    cell.appendChild(img);
    if(!lit){ var lock=mk('div','position:absolute;left:50%;top:52%;transform:translate(-50%,-50%);font-size:'+Math.round(px*0.26)+'px;line-height:1;text-shadow:0 1px 3px #000;','🔒');
    cell.appendChild(lock); }
    return cell; }
    // The TROPHY COLLECTION block appended inside the achievements overlay.
    function spTrophySection(pad){ try{
    pad.appendChild(mk('div',FS(9,'#e2b23a')+'letter-spacing:1px;margin:22px 0 4px;','TROPHY COLLECTION '+spTrophyCount()+'/9'));
    pad.appendChild(mk('div','font-size:10px;line-height:1.5;color:#8a7fb0;margin-bottom:10px;','Clear a season final to mint its cup — bronze on Easy, silver on Medium, gold on Hard.'));
    var LVN=['EASY','MED','HARD'];
    for(var s=0;s<3;s++){ var d=royDiffsFor(s+1)||[];
    var srow=mk('div','margin-bottom:11px;padding:10px 9px 7px;border-radius:10px;border:2px solid #2a2438;background:rgba(255,255,255,0.02);');
    srow.appendChild(mk('div',FS(7,'#c9bce0')+'letter-spacing:1px;margin-bottom:7px;',TROPHY_SEASONS[s]));
    var grid=mk('div','display:flex;justify-content:space-around;align-items:flex-end;gap:6px;');
    for(var t=0;t<3;t++){ var lit=d.indexOf(TROPHY_DIFFS[t])>=0;
    var col=mk('div','flex:1;display:flex;flex-direction:column;align-items:center;');
    col.appendChild(spTrophyEl(s,t,lit,92));
    col.appendChild(mk('div',FS(6,lit?'#e2b23a':'#5a5470')+'margin-top:3px;',LVN[t]));
    grid.appendChild(col); }
    srow.appendChild(grid); pad.appendChild(srow); }
    }catch(e){} }
    /* Blit the best trophy a player has earned for `season` onto the Royale map
       at canvas (x,y), scaled to `size`. Draws nothing until the sprite loads or
       if the season is unwon, so the summit just shows the baked-in art. Picks
       the highest difficulty cleared (gold>silver>bronze). */
    function spTrophyMapBadge(g,x,y,size,season){ try{ var d=royDiffsFor(season)||[];
    var ti=-1; for(var t=2;t>=0;t--){ if(d.indexOf(TROPHY_DIFFS[t])>=0){ ti=t; break; } }
    if(ti<0) return false; var im=spTrophyImg(season-1,ti);
    if(!im||!im.complete||!im.naturalWidth) return false;
    var s2=size, hx=x-s2/2, hy=y-s2/2;
    g.save(); g.beginPath(); g.arc(x,y,s2*0.5,0,6.28); g.closePath(); g.clip();
    g.drawImage(im,hx,hy,s2,s2); g.restore();
    g.strokeStyle='rgba(242,201,76,0.9)'; g.lineWidth=Math.max(1.5,size*0.03);
    g.beginPath(); g.arc(x,y,s2*0.5,0,6.28); g.stroke();
    return true; }catch(e){ return false; } }
