    /* ---- TROPHY COLLECTION ----------------------------------------------
       Nine hand-generated pixel-art cups: 3 season finals x bronze/silver/gold
       (easy/med/hard). Each cup wears the hazards of the final you beat. Art is
       generated by tools/gen-trophies.mjs and shipped to
       assets/generated/trophy-s{1,2,3}-{bronze,silver,gold}.png, preloaded into
       NS_TROPHIES (see 12-draw.js). A trophy is "earned" once that season has
       been cleared at that difficulty (royDiffsFor). Shown in the achievements
       overlay and blitted onto the Royale map summit. */
    var TROPHY_METALS=['bronze','silver','gold'];        // easy / med / hard
    var TROPHY_SEASONS=['S1 THE FINAL','S2 THE TURF','S3 SPORTS DAY'];
    var TROPHY_DIFFS=['easy','med','hard'];
    // The preloaded Image for season index si (0-2) and tier ti (0-2), or null.
    function spTrophyImg(si,ti){ try{ return NS_TROPHIES['s'+(si+1)+'-'+TROPHY_METALS[ti]]||null;
    }catch(e){ return null; } }
    // How many of the 9 trophies the player has earned (season+diff cleared).
    function spTrophyCount(){ try{ var n=0;
    for(var s=1;s<=3;s++){ var d=royDiffsFor(s)||[];
    for(var t=0;t<3;t++){ if(d.indexOf(TROPHY_DIFFS[t])>=0) n++; } } return n;
    }catch(e){ return 0; } }
    // A ready-to-place DOM cell carrying one trophy at pixel size px. Locked
    // trophies render greyed + dimmed with a small padlock so the shape still
    // teases what's on offer.
    function spTrophyEl(si,ti,lit,px){ var cell=mk('div','position:relative;width:'+px+'px;height:'+px+'px;');
    var im=spTrophyImg(si,ti);
    var img=mk('img','width:100%;height:100%;image-rendering:pixelated;display:block;'+(lit?'':'filter:grayscale(1) brightness(0.4) contrast(0.9);opacity:0.6;'));
    try{ if(im&&im.src) img.src=im.src; }catch(e){}
    cell.appendChild(img);
    if(!lit){ var lock=mk('div','position:absolute;left:50%;top:52%;transform:translate(-50%,-50%);font-size:'+Math.round(px*0.26)+'px;line-height:1;text-shadow:0 1px 3px #000;','🔒');
    cell.appendChild(lock); }
    return cell; }
    // The TROPHY COLLECTION block appended inside the achievements overlay.
    function spTrophySection(pad){ try{
    pad.appendChild(mk('div',FS(9,'#e2b23a')+'letter-spacing:1px;margin:22px 0 4px;','TROPHY COLLECTION '+spTrophyCount()+'/9'));
    pad.appendChild(mk('div','font-size:10px;line-height:1.5;color:#8a7fb0;margin-bottom:10px;','Clear a season final to mint its cup — bronze on Easy, silver on Medium, gold on Hard.'));
    var LVN=['EASY','MED','HARD'];
    for(var s=0;s<3;s++){ var d=royDiffsFor(s+1)||[];
    var srow=mk('div','margin-bottom:11px;padding:10px 9px 7px;border-radius:10px;border:2px solid #2a2438;background:rgba(255,255,255,0.02);');
    srow.appendChild(mk('div',FS(7,'#c9bce0')+'letter-spacing:1px;margin-bottom:7px;',TROPHY_SEASONS[s]));
    var grid=mk('div','display:flex;justify-content:space-around;align-items:flex-end;gap:6px;');
    for(var t=0;t<3;t++){ var lit=d.indexOf(TROPHY_DIFFS[t])>=0;
    var col=mk('div','flex:1;display:flex;flex-direction:column;align-items:center;');
    col.appendChild(spTrophyEl(s,t,lit,92));
    col.appendChild(mk('div',FS(6,lit?'#e2b23a':'#5a5470')+'margin-top:3px;',LVN[t]));
    grid.appendChild(col); }
    srow.appendChild(grid); pad.appendChild(srow); }
    }catch(e){} }
    /* Champion-screen reward: the just-cleared season's three difficulty cups
       (bronze/silver/gold = easy/med/hard), the one you earned this run lifted
       bigger, ringed and tagged, the others lit if already earned or greyed if
       still locked — so beating a season boss shows the trophy you won AND what
       the season still has on offer. Returns a DOM node, or null. */
    function spTrophyEarnedPanel(season, lvl){ try{
    var si=season-1, nti=(lvl==='easy')?0:((lvl==='hard')?2:1);
    var d=royDiffsFor(season)||[], LVN=['EASY','MED','HARD'];
    var wrap=mk('div','width:100%;max-width:290px;margin:6px 0 2px;padding:12px 12px 10px;border-radius:12px;border:2px solid '+_TROPHY_RING[nti]+';background:rgba(255,255,255,0.03);display:flex;flex-direction:column;align-items:center;gap:7px;');
    wrap.appendChild(mk('div',FS(9,_TROPHY_RING[nti])+'letter-spacing:1px;text-shadow:0 2px 0 #1c1330;','TROPHY EARNED'));
    wrap.appendChild(mk('div',FS(7,'#c9bce0')+'letter-spacing:1px;',TROPHY_SEASONS[si]));
    var grid=mk('div','display:flex;justify-content:space-around;align-items:flex-end;gap:10px;width:100%;');
    for(var t=0;t<3;t++){ var lit=d.indexOf(TROPHY_DIFFS[t])>=0, isNew=(t===nti);
    var col=mk('div','flex:1;display:flex;flex-direction:column;align-items:center;gap:3px;');
    var cell=spTrophyEl(si,t,lit,isNew?96:64);
    if(isNew) cell.style.cssText+=';border-radius:12px;box-shadow:0 0 0 2px '+_TROPHY_RING[nti]+',0 0 14px '+_TROPHY_RING[nti]+';';
    col.appendChild(cell);
    col.appendChild(mk('div',FS(6,lit?'#e2b23a':'#5a5470')+'letter-spacing:0.5px;',LVN[t]+(isNew?' ✦':'')));
    grid.appendChild(col); }
    wrap.appendChild(grid);
    wrap.appendChild(mk('div',FS(6,'#8a7fb0')+'letter-spacing:1px;margin-top:2px;','COLLECTION '+spTrophyCount()+'/9'));
    return wrap;
    }catch(e){ return null; } }
    /* Where the painted trophy sits in each season's map art (fractions of the
       map canvas: x of width, y+r of height). The dynamic cup is drawn as a
       medallion here to REPLACE the generic gold cup baked into the art, so the
       summit always shows the real, difficulty-specific trophy. Tuned visually
       against roymap*.png — re-check if a map is regenerated. */
    var _ROY_SUMMIT={1:{x:0.843,y:0.078,r:0.084},2:{x:0.857,y:0.076,r:0.084},3:{x:0.808,y:0.092,r:0.100}};
    var _TROPHY_RING=['#d0904a','#c8cdd6','#f2c94c'];  // bronze / silver / gold rim
    /* Draw the CURRENT difficulty's cup for `season` as a summit medallion on the
       Royale map, over the baked-in art trophy. Always shown (it is the prize on
       offer); a green tick marks it once that difficulty is cleared. cw,ch are the
       map canvas size. */
    function spTrophyMapBadge(g,cw,ch,season){ try{ var C=_ROY_SUMMIT[season];
    if(!C) return false; var lvl=(typeof royaleLevel!=='undefined'?royaleLevel:'med');
    var ti=(lvl==='easy')?0:((lvl==='hard')?2:1);
    var im=spTrophyImg(season-1,ti); if(!im||!im.complete||!im.naturalWidth) return false;
    var x=C.x*cw, y=C.y*ch, R=C.r*ch;
    var earned=(royDiffsFor(season)||[]).indexOf(lvl)>=0;
    g.save();
    g.globalAlpha=0.4; g.fillStyle='#000'; g.beginPath(); g.arc(x,y+R*0.12,R*1.03,0,6.28); g.fill(); g.globalAlpha=1;
    g.fillStyle='#0e0b16'; g.beginPath(); g.arc(x,y,R,0,6.28); g.fill();
    g.save(); g.beginPath(); g.arc(x,y,R*0.93,0,6.28); g.clip();
    var d=R*2*1.04; g.drawImage(im,x-d/2,y-d/2,d,d); g.restore();
    g.lineWidth=Math.max(2,R*0.11); g.strokeStyle=_TROPHY_RING[ti];
    g.beginPath(); g.arc(x,y,R*0.95,0,6.28); g.stroke();
    if(earned){ var bx=x+R*0.66, by=y+R*0.66, br=R*0.30;
    g.fillStyle='#2a8a34'; g.beginPath(); g.arc(bx,by,br,0,6.28); g.fill();
    g.lineWidth=Math.max(1.5,R*0.06); g.strokeStyle='#eafce0';
    g.beginPath(); g.moveTo(bx-br*0.45,by); g.lineTo(bx-br*0.08,by+br*0.42); g.lineTo(bx+br*0.5,by-br*0.42); g.stroke();
    } g.restore(); return true; }catch(e){ return false; } }
